//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class alccost
    {
        public int alcid { get; set; }
        public string ccode { get; set; }
        public string bcode { get; set; }
        public string book { get; set; }
        public string doc { get; set; }
        public string alc_refno { get; set; }
        public Nullable<System.DateTime> alcdate_save { get; set; }
        public Nullable<System.DateTime> alcdate_sum { get; set; }
        public string alc_status { get; set; }
        public string alc_post { get; set; }
        public string doc_s { get; set; }
        public string doc_e { get; set; }
        public Nullable<System.DateTime> alcdate_s { get; set; }
        public Nullable<System.DateTime> alcdate_e { get; set; }
        public string note1 { get; set; }
        public string note2 { get; set; }
        public string note3 { get; set; }
        public string note4 { get; set; }
        public string note5 { get; set; }
        public string note6 { get; set; }
        public string note7 { get; set; }
        public string note8 { get; set; }
        public string note9 { get; set; }
        public string note10 { get; set; }
        public string note11 { get; set; }
        public string note12 { get; set; }
        public string note13 { get; set; }
        public string note14 { get; set; }
        public string note15 { get; set; }
        public string note16 { get; set; }
        public string note17 { get; set; }
        public string note18 { get; set; }
        public string note19 { get; set; }
        public string note20 { get; set; }
    }
}
