//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class APSMyMenu
    {
        public int id { get; set; }
        public string Thname { get; set; }
        public string Enname { get; set; }
        public string Frmname { get; set; }
        public string FrmMenu { get; set; }
        public Nullable<int> TypeAD { get; set; }
    }
}
