//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AROption
    {
        public int BrchID { get; set; }
        public string AgingCust { get; set; }
        public string ArRecpNo { get; set; }
        public string ArOverRece { get; set; }
        public string ArOverSO { get; set; }
        public string ccode { get; set; }
    }
}
