//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASP_Permission_Menu_Users
    {
        public Nullable<int> user_id { get; set; }
        public string user_name { get; set; }
        public string menu_name { get; set; }
        public string menu_form { get; set; }
        public Nullable<int> status_grant { get; set; }
        public Nullable<int> btn_add { get; set; }
        public Nullable<int> btn_edit { get; set; }
        public Nullable<int> btn_del { get; set; }
        public Nullable<int> btn_print { get; set; }
        public Nullable<int> btn_recal { get; set; }
        public Nullable<int> btn_cancel { get; set; }
        public Nullable<int> btn_book { get; set; }
    }
}
