//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit
    {
        public int audit_id { get; set; }
        public Nullable<int> audit_system { get; set; }
        public Nullable<int> audit_screen { get; set; }
        public Nullable<System.DateTime> audit_datetime { get; set; }
        public string audit_username { get; set; }
        public string audit_action { get; set; }
        public string audit_docno { get; set; }
        public string audit_bookno { get; set; }
        public Nullable<System.DateTime> audit_docdate { get; set; }
        public string audit_computername { get; set; }
        public string audit_computerIPadd { get; set; }
        public string audit_query { get; set; }
        public string ccode { get; set; }
        public string bcode { get; set; }
        public string audit_formname { get; set; }
        public string audit_type { get; set; }
        public Nullable<int> eid { get; set; }
    }
}
