//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public int b_id { get; set; }
        public string ccode { get; set; }
        public string bcode { get; set; }
        public string bname1 { get; set; }
        public string bname12 { get; set; }
        public string bname2 { get; set; }
        public string bname22 { get; set; }
        public string baddress1 { get; set; }
        public string baddress2 { get; set; }
        public string bzip { get; set; }
        public string btel { get; set; }
        public string bfax { get; set; }
        public string wcode { get; set; }
        public Nullable<int> postformat { get; set; }
        public Nullable<int> sp_num { get; set; }
    }
}
