//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class causeLose_pm
    {
        public int cl_id { get; set; }
        public int sym_id { get; set; }
        public string clcode { get; set; }
        public string ccode { get; set; }
        public string symcode { get; set; }
        public string clDetail { get; set; }
        public string clRemark { get; set; }
    }
}
