//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class crepdoc_pm
    {
        public int crep_id { get; set; }
        public string crepdoc { get; set; }
        public string crepname { get; set; }
        public string bcode { get; set; }
        public string ccode { get; set; }
        public string wcode { get; set; }
        public string scode { get; set; }
    }
}
