//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerZone
    {
        public int cuszid { get; set; }
        public string cuszcode { get; set; }
        public string cuszname1 { get; set; }
        public string cuszname2 { get; set; }
        public string ccode { get; set; }
    }
}
