//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depart
    {
        public int d_id { get; set; }
        public string dcode { get; set; }
        public string dname1 { get; set; }
        public string dname2 { get; set; }
        public string ccode { get; set; }
    }
}
