//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class door
    {
        public int ID { get; set; }
        public string wcode { get; set; }
        public Nullable<decimal> locationx { get; set; }
        public Nullable<decimal> locationy { get; set; }
        public Nullable<int> Rostat { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
