//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMTranspArea
    {
        public int TranspAreaID { get; set; }
        public string TranspAreaCode { get; set; }
        public string TranspAreaName { get; set; }
        public string TranspAreaNameEng { get; set; }
        public string Remark { get; set; }
        public string ccode { get; set; }
    }
}
