//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EOQ_warehouse
    {
        public int r_id { get; set; }
        public string wcode { get; set; }
        public Nullable<decimal> max { get; set; }
        public Nullable<decimal> min { get; set; }
        public Nullable<decimal> safty { get; set; }
        public Nullable<decimal> reorder { get; set; }
        public Nullable<decimal> eoq { get; set; }
    }
}
