//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public int id { get; set; }
        public string fName { get; set; }
        public string fType { get; set; }
        public Nullable<int> w { get; set; }
        public Nullable<int> h { get; set; }
        public Nullable<int> h1 { get; set; }
        public Nullable<int> h2 { get; set; }
        public Nullable<int> h3 { get; set; }
        public Nullable<int> h4 { get; set; }
        public Nullable<int> h5 { get; set; }
        public Nullable<int> l { get; set; }
        public Nullable<int> t { get; set; }
        public Nullable<int> r { get; set; }
        public Nullable<int> b { get; set; }
    }
}
