//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gmachine
    {
        public int gm_id { get; set; }
        public string gmcode { get; set; }
        public string gmname1 { get; set; }
        public string gmname2 { get; set; }
        public string ccode { get; set; }
        public string bcode { get; set; }
        public string fcode { get; set; }
        public string secode { get; set; }
        public Nullable<decimal> gmcap { get; set; }
        public Nullable<decimal> LotSize { get; set; }
        public Nullable<decimal> BatchSize { get; set; }
        public Nullable<decimal> QueueTime { get; set; }
        public Nullable<decimal> SetupTime { get; set; }
        public Nullable<decimal> ProcessingTime { get; set; }
        public Nullable<decimal> TeardownTime { get; set; }
        public Nullable<decimal> WaitTime { get; set; }
        public Nullable<decimal> MoveTime { get; set; }
        public string ucode { get; set; }
        public string utime { get; set; }
        public string color { get; set; }
    }
}
