//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class grnDetail
    {
        public string grnID { get; set; }
        public string pID { get; set; }
        public string lot { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> qty2 { get; set; }
        public Nullable<decimal> price { get; set; }
        public string discount { get; set; }
        public Nullable<decimal> total { get; set; }
        public string seq { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string remark3 { get; set; }
        public string remark4 { get; set; }
        public string remark5 { get; set; }
        public string remark6 { get; set; }
        public string remark7 { get; set; }
        public string remark8 { get; set; }
        public string remark9 { get; set; }
        public string remark10 { get; set; }
        public string wcode { get; set; }
        public string PF { get; set; }
        public string tagID { get; set; }
        public Nullable<System.DateTime> deliveryDay { get; set; }
        public string bcode { get; set; }
        public string ccode { get; set; }
        public Nullable<int> bciid { get; set; }
        public Nullable<int> sunitid { get; set; }
        public Nullable<decimal> Std_cost { get; set; }
    }
}
