//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groupproduct5
    {
        public int bciid { get; set; }
        public string grpcode { get; set; }
        public string grpname1 { get; set; }
        public string grpname2 { get; set; }
        public Nullable<int> grpcountstock { get; set; }
        public string ccode { get; set; }
    }
}
