//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public int hid { get; set; }
        public string ccode { get; set; }
        public string bcode { get; set; }
        public string fcode { get; set; }
        public Nullable<System.DateTime> hdate { get; set; }
        public string description { get; set; }
        public string maccode { get; set; }
    }
}
