//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int loc_id { get; set; }
        public string loccode { get; set; }
        public string wcode { get; set; }
        public string locname1 { get; set; }
        public string locname2 { get; set; }
        public string locname11 { get; set; }
        public string locname12 { get; set; }
        public string loctype { get; set; }
        public string bcode { get; set; }
        public string ccode { get; set; }
        public Nullable<decimal> loc_canvasLeft { get; set; }
        public Nullable<decimal> loc_canvasTop { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Lenght { get; set; }
        public Nullable<int> Rotate { get; set; }
        public Nullable<int> NumOfRack { get; set; }
        public Nullable<int> NumOfColumn { get; set; }
        public string Note1 { get; set; }
        public string Note2 { get; set; }
        public string Note3 { get; set; }
        public string Note4 { get; set; }
        public string Note5 { get; set; }
        public string Note6 { get; set; }
        public string Note7 { get; set; }
        public string Note8 { get; set; }
        public string Note9 { get; set; }
        public string Note10 { get; set; }
    }
}
