//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machinept
    {
        public int mpt_id { get; set; }
        public string mptcode { get; set; }
        public string mptname1 { get; set; }
        public string mptname2 { get; set; }
        public string bcode { get; set; }
        public string fcode { get; set; }
    }
}
