//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class McGM
    {
        public int mcgm_id { get; set; }
        public string ccode { get; set; }
        public string bcode { get; set; }
        public string fcode { get; set; }
        public string secode { get; set; }
        public Nullable<int> mostatus { get; set; }
        public string mobook { get; set; }
        public string modoc { get; set; }
        public string book { get; set; }
        public string doc { get; set; }
        public string ref_no { get; set; }
        public Nullable<System.DateTime> MCdate { get; set; }
        public string cuscode { get; set; }
        public string pcode { get; set; }
        public string bomcode { get; set; }
        public Nullable<decimal> num1 { get; set; }
        public Nullable<decimal> num2 { get; set; }
        public Nullable<decimal> scrap { get; set; }
        public string TagId { get; set; }
        public Nullable<System.DateTime> date1 { get; set; }
        public Nullable<System.DateTime> date2 { get; set; }
        public Nullable<System.DateTime> Exdate { get; set; }
        public Nullable<System.DateTime> Etddate { get; set; }
        public Nullable<decimal> payment1 { get; set; }
        public Nullable<decimal> payment2 { get; set; }
        public Nullable<decimal> payment3 { get; set; }
        public Nullable<decimal> payment4 { get; set; }
        public Nullable<decimal> payment5 { get; set; }
        public Nullable<decimal> payment6 { get; set; }
        public Nullable<decimal> payment7 { get; set; }
        public Nullable<decimal> payment8 { get; set; }
        public Nullable<decimal> total_payment { get; set; }
        public Nullable<int> createrfg { get; set; }
        public Nullable<int> creatercw { get; set; }
        public Nullable<int> MCstate { get; set; }
        public string statusMC { get; set; }
        public string note1 { get; set; }
        public string note2 { get; set; }
        public string note3 { get; set; }
        public string note4 { get; set; }
        public string note5 { get; set; }
        public string note6 { get; set; }
        public string note7 { get; set; }
        public string note8 { get; set; }
        public string note9 { get; set; }
        public string note10 { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
    }
}
