//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDAcc
    {
        public int AccID { get; set; }
        public Nullable<int> AccTypeID { get; set; }
        public Nullable<int> AccCashID { get; set; }
        public Nullable<int> AccFinanID { get; set; }
        public Nullable<int> AccStrucID { get; set; }
        public string AccCode { get; set; }
        public Nullable<int> AccControlID { get; set; }
        public string AccName { get; set; }
        public string AccNameEng { get; set; }
        public string AccGroup { get; set; }
        public string AccLevel { get; set; }
        public string AccControlFlag { get; set; }
        public string AccBalnDrCr { get; set; }
        public string AccHaveAlloc { get; set; }
        public string AccHaveQty { get; set; }
        public string AccStrucCode { get; set; }
        public string AccHaveDept { get; set; }
        public string AccHaveJob { get; set; }
        public string CloseAcc { get; set; }
        public string ccode { get; set; }
    }
}
