//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDAccType
    {
        public int AccTypeID { get; set; }
        public string AccTypeName { get; set; }
        public string Remark { get; set; }
        public string AccTypeNameEng { get; set; }
        public string AccTypeCode { get; set; }
        public string ccode { get; set; }
    }
}
