//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDBankBrch
    {
        public int BankBrchID { get; set; }
        public string BankBrchCode { get; set; }
        public string BankBrchName { get; set; }
        public string BankBrchNameEng { get; set; }
        public string BankBrchAddr1 { get; set; }
        public string BankBrchAddr2 { get; set; }
        public string Remark { get; set; }
        public string ccode { get; set; }
    }
}
