//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDBank
    {
        public int BankID { get; set; }
        public string BankCode { get; set; }
        public string BankName { get; set; }
        public string BankNameEng { get; set; }
        public string TaxCode { get; set; }
        public string CompNo { get; set; }
        public Nullable<int> CheqPicID { get; set; }
        public Nullable<int> PayInPicID { get; set; }
        public Nullable<int> PayOutPicID { get; set; }
        public string NationalFlag { get; set; }
        public string BankNo { get; set; }
        public string CompnetID { get; set; }
        public string ShowType { get; set; }
        public string ccode { get; set; }
    }
}
