//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDBranch
    {
        public int b_id { get; set; }
        public string CodeBranch { get; set; }
        public string BranchType { get; set; }
        public int NumBranch { get; set; }
        public string NameBranch { get; set; }
        public string InitialsBranch { get; set; }
        public string NameBranch2 { get; set; }
        public string InitialsBranch2 { get; set; }
        public string AdBranch { get; set; }
        public string AdBranch2 { get; set; }
        public string PostBranch { get; set; }
        public string TelBranch { get; set; }
        public string FaxBranch { get; set; }
        public string NoteBranch { get; set; }
        public string ccode { get; set; }
    }
}
