//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDCostCode
    {
        public int CostCode_id { get; set; }
        public string CodeCostCODE { get; set; }
        public string NameTH_CostCODE { get; set; }
        public string NameEN_CostCODE { get; set; }
        public int Code_Account_ID { get; set; }
        public string Remark { get; set; }
    }
}
