//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDCusType
    {
        public int CusTypeID { get; set; }
        public string CusTypeCode { get; set; }
        public string CusTypeName { get; set; }
        public string CusTypeNameEng { get; set; }
        public string Remark { get; set; }
        public string ccode { get; set; }
    }
}
