//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDCusContact
    {
        public int ContactID { get; set; }
        public string ContactName { get; set; }
        public int ListNo { get; set; }
        public string Remark { get; set; }
        public int CusID { get; set; }
        public string Tel { get; set; }
        public string ContactPost { get; set; }
        public string ContactDuty { get; set; }
        public string ContactAddr1 { get; set; }
        public string ContactAddr2 { get; set; }
        public string IsDefault { get; set; }
        public string ContactEmail { get; set; }
    }
}
