//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDCusTempCreditHD
    {
        public int CreditID { get; set; }
        public string DocNo { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> CreditStartDate { get; set; }
        public Nullable<System.DateTime> CreditEndDate { get; set; }
        public string Remark { get; set; }
        public string CancelFlag { get; set; }
        public string ccode { get; set; }
    }
}
