//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDEmpGroup
    {
        public int EmpGroupID { get; set; }
        public string EmpGroupCode { get; set; }
        public string EmpGroupName { get; set; }
        public string EmpGroupNameEng { get; set; }
        public string Remark { get; set; }
        public string ccode { get; set; }
    }
}
