//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDEmGroup
    {
        public int EmGroupID { get; set; }
        public string EmCode { get; set; }
        public string EmGroupName { get; set; }
        public string EmGroupNameEng { get; set; }
        public string EmGroupNote { get; set; }
        public string ccode { get; set; }
    }
}
