//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDEmpApprovPOHD
    {
        public int ApprvPOID { get; set; }
        public string ApprvPOCode { get; set; }
        public int ApprovAmnt { get; set; }
        public string EmpCode { get; set; }
        public string Remark { get; set; }
        public string ApprovName { get; set; }
        public string ccode { get; set; }
    }
}
