//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDEmPosition
    {
        public int EmPositionID { get; set; }
        public string EmPositionCode { get; set; }
        public string EmPositionName { get; set; }
        public string EmPositionNameEng { get; set; }
        public string EmPositionNote { get; set; }
        public string ccode { get; set; }
    }
}
