//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDPosition
    {
        public int PostID { get; set; }
        public string PostCode { get; set; }
        public string PostName { get; set; }
        public string PostNameEng { get; set; }
        public string Remark { get; set; }
        public string ccode { get; set; }
    }
}
