//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDRun
    {
        public string RunCode { get; set; }
        public string RunName { get; set; }
        public string RunNameENG { get; set; }
        public string RunFormat { get; set; }
        public string RunColumn { get; set; }
        public string HaveBrch { get; set; }
        public string IsGL { get; set; }
        public Nullable<int> SystemFlag { get; set; }
        public string ccode { get; set; }
    }
}
