//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDSalesArea
    {
        public int SalesAreaID { get; set; }
        public string SalesAreaCode { get; set; }
        public string SalesAreaName { get; set; }
        public string SalesAreaNameEng { get; set; }
        public string SalesAreaNote { get; set; }
        public string ccode { get; set; }
    }
}
