//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDSupplierType
    {
        public int SupplierTypeID { get; set; }
        public string SupplierTypeCode { get; set; }
        public string SupplierTypeName { get; set; }
        public string SupplierTypeENG { get; set; }
        public string Remark { get; set; }
        public string ccode { get; set; }
    }
}
