//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDTransportationzone
    {
        public int TransportationID { get; set; }
        public string TransportationCode { get; set; }
        public string TransportationName { get; set; }
        public string TransportationNameEng { get; set; }
        public string TransportationNote { get; set; }
        public string ccode { get; set; }
    }
}
