//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDVATGroup
    {
        public int VATGroupID { get; set; }
        public string VATGroupCode { get; set; }
        public string AccCode { get; set; }
        public Nullable<double> VatRate { get; set; }
        public string VatType { get; set; }
        public string Remark { get; set; }
        public string ReportName { get; set; }
        public string ccode { get; set; }
    }
}
