//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDVatOption
    {
        public int LinkID { get; set; }
        public string Linkcode { get; set; }
        public string Postvat { get; set; }
        public string SoPostNonVat { get; set; }
        public string bcode { get; set; }
        public string ccode { get; set; }
    }
}
