//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int menuid { get; set; }
        public string menuname { get; set; }
        public string frmname { get; set; }
        public string frmMenuname { get; set; }
        public string frmsubMenuname { get; set; }
    }
}
