//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovementTableIn
    {
        public int id { get; set; }
        public string pcode { get; set; }
        public Nullable<double> rAmount { get; set; }
        public Nullable<double> rCost { get; set; }
        public string lot { get; set; }
    }
}
