//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovementTable
    {
        public int id { get; set; }
        public string doc { get; set; }
        public string pcode { get; set; }
        public string docdate { get; set; }
        public string rAmount { get; set; }
        public string rCost { get; set; }
        public string rMoney { get; set; }
        public string pAmount { get; set; }
        public string pCost { get; set; }
        public string pMoney { get; set; }
        public string allAmount { get; set; }
        public string allCost { get; set; }
        public string allMoney { get; set; }
        public string lot { get; set; }
        public string bcode { get; set; }
        public string ccode { get; set; }
    }
}
