//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class movement
    {
        public string mid { get; set; }
        public System.DateTime mdate1 { get; set; }
        public System.DateTime mdate2 { get; set; }
        public int num1 { get; set; }
        public int num2 { get; set; }
    }
}
