//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MpM
    {
        public int mpm_id { get; set; }
        public string ccode { get; set; }
        public string bcode { get; set; }
        public string fcode { get; set; }
        public string secode { get; set; }
        public Nullable<int> @ref { get; set; }
        public string ref_book { get; set; }
        public string ref_doc { get; set; }
        public string book { get; set; }
        public string doc { get; set; }
        public string ref_no { get; set; }
        public Nullable<System.DateTime> MPdate { get; set; }
        public string cuscode { get; set; }
        public string pcode { get; set; }
        public string bomcode { get; set; }
        public Nullable<decimal> num1 { get; set; }
        public Nullable<decimal> num2 { get; set; }
        public Nullable<decimal> scrap { get; set; }
        public string TagId { get; set; }
        public Nullable<System.DateTime> date1 { get; set; }
        public Nullable<System.DateTime> date2 { get; set; }
        public Nullable<System.DateTime> Exdate { get; set; }
        public Nullable<System.DateTime> Etddate { get; set; }
        public string status1 { get; set; }
        public string status2 { get; set; }
        public string status3 { get; set; }
        public string statusMP { get; set; }
        public Nullable<int> createB { get; set; }
        public Nullable<int> createC { get; set; }
        public Nullable<int> MPstate { get; set; }
        public string note1 { get; set; }
        public string note2 { get; set; }
        public string note3 { get; set; }
        public string note4 { get; set; }
        public string note5 { get; set; }
        public string note6 { get; set; }
        public string note7 { get; set; }
        public string note8 { get; set; }
        public string note9 { get; set; }
        public string note10 { get; set; }
        public Nullable<int> mpmgenid { get; set; }
        public string statusLT { get; set; }
        public string TypeSale { get; set; }
        public Nullable<int> Proof { get; set; }
        public Nullable<int> pro_id { get; set; }
        public Nullable<int> StepMP { get; set; }
        public string LotFG { get; set; }
        public Nullable<int> typeExpose { get; set; }
    }
}
