//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPM_RawMat
    {
        public int mpm_id { get; set; }
        public string pcode { get; set; }
        public Nullable<decimal> num1 { get; set; }
        public Nullable<decimal> num2 { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<decimal> pbook { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
    }
}
