//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRP_SubMenu
    {
        public string SubMenuCode { get; set; }
        public string SubMenuName1 { get; set; }
        public string SubMenuName2 { get; set; }
    }
}
