//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mrp_bookFG_detail
    {
        public int book_id { get; set; }
        public string pcode { get; set; }
        public Nullable<decimal> num1 { get; set; }
        public Nullable<decimal> num2 { get; set; }
        public string wcode { get; set; }
        public string lot_id { get; set; }
        public string tag_id { get; set; }
        public Nullable<int> status_do { get; set; }
        public Nullable<decimal> num_do { get; set; }
    }
}
