//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mrp_bookFG
    {
        public int book_id { get; set; }
        public string doc { get; set; }
        public string ref_no { get; set; }
        public Nullable<System.DateTime> book_date { get; set; }
        public string type_doc { get; set; }
        public Nullable<int> so_id { get; set; }
        public Nullable<int> status_do { get; set; }
    }
}
