//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mts
    {
        public int Mis_id { get; set; }
        public string ccode { get; set; }
        public string bcode { get; set; }
        public string doc { get; set; }
        public string pr { get; set; }
        public string pr_no { get; set; }
        public Nullable<System.DateTime> mis_date { get; set; }
        public string dcode { get; set; }
        public string hrwork { get; set; }
        public string pass { get; set; }
        public string hrpass { get; set; }
        public Nullable<System.DateTime> passdate { get; set; }
        public string note1 { get; set; }
        public string note2 { get; set; }
        public string note3 { get; set; }
        public string note4 { get; set; }
        public string note5 { get; set; }
        public string note6 { get; set; }
        public string note7 { get; set; }
        public string note8 { get; set; }
        public string note9 { get; set; }
        public string note10 { get; set; }
        public Nullable<int> mtsstate { get; set; }
        public string ref_no { get; set; }
        public Nullable<int> genmp { get; set; }
        public string secode { get; set; }
    }
}
