//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mts_details
    {
        public int Mis_id { get; set; }
        public string pcode { get; set; }
        public string pname1 { get; set; }
        public Nullable<decimal> num1 { get; set; }
        public string num1detail { get; set; }
        public Nullable<decimal> num2 { get; set; }
        public string num2detail { get; set; }
        public Nullable<System.DateTime> finnishdate { get; set; }
        public string note1 { get; set; }
        public string note2 { get; set; }
        public string note3 { get; set; }
        public string note4 { get; set; }
        public string note5 { get; set; }
        public string note6 { get; set; }
        public string note7 { get; set; }
        public string note8 { get; set; }
        public string note9 { get; set; }
        public string note10 { get; set; }
        public Nullable<System.DateTime> saleDate { get; set; }
        public string TagId { get; set; }
        public string lot { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> num0 { get; set; }
        public Nullable<int> genmp { get; set; }
    }
}
