//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paret
    {
        public int ParetID { get; set; }
        public string PID { get; set; }
        public string paretName { get; set; }
        public string Approvestatus { get; set; }
        public Nullable<decimal> pweight { get; set; }
        public Nullable<decimal> pheight { get; set; }
        public Nullable<decimal> pleight { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<decimal> ptotal { get; set; }
    }
}
