//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pdst
    {
        public int bomid { get; set; }
        public string bomcode { get; set; }
        public string bomname1 { get; set; }
        public string bomname2 { get; set; }
        public string bname1 { get; set; }
        public string fname1 { get; set; }
        public string bomstatus { get; set; }
        public Nullable<System.DateTime> bomdt { get; set; }
        public string bombp { get; set; }
        public Nullable<decimal> bombatch { get; set; }
        public string bomproduce { get; set; }
        public string gmname1 { get; set; }
        public string macname1 { get; set; }
        public string bomtype { get; set; }
        public Nullable<decimal> bomsize { get; set; }
        public string uname1 { get; set; }
        public string pcode { get; set; }
        public string ccode { get; set; }
        public Nullable<int> waittime { get; set; }
        public string maccode02 { get; set; }
        public Nullable<decimal> sizebatch { get; set; }
        public Nullable<decimal> lossRM { get; set; }
        public Nullable<int> ExposeType { get; set; }
    }
}
