//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pm_adjust
    {
        public int adj_id { get; set; }
        public string ccode { get; set; }
        public string book_no { get; set; }
        public string doc_no { get; set; }
        public string ref_no { get; set; }
        public Nullable<System.DateTime> adj_date { get; set; }
        public Nullable<int> emp_adj { get; set; }
        public string emp_adj_name { get; set; }
        public Nullable<int> status_doc { get; set; }
        public Nullable<int> sec_id { get; set; }
        public string note01 { get; set; }
        public string note02 { get; set; }
        public string note03 { get; set; }
        public string note04 { get; set; }
        public string note05 { get; set; }
        public string note06 { get; set; }
        public string note07 { get; set; }
        public string note08 { get; set; }
        public string note09 { get; set; }
        public string note10 { get; set; }
        public Nullable<int> approve_type { get; set; }
        public Nullable<int> emp_approve { get; set; }
        public string emp_approve_name { get; set; }
    }
}
