//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pm_groupline
    {
        public int gl_id { get; set; }
        public string gl_code { get; set; }
        public string gl_name { get; set; }
        public string gl_remark { get; set; }
    }
}
