//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM_group_machine
    {
        public int grpmchid { get; set; }
        public string grpmchcode { get; set; }
        public string grpmchname1 { get; set; }
        public string grpmchname2 { get; set; }
        public string grpmchremark { get; set; }
        public string ccode { get; set; }
        public string bcode { get; set; }
    }
}
