//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pm_issue
    {
        public int issue_id { get; set; }
        public string ccode { get; set; }
        public string book_no { get; set; }
        public string doc_no { get; set; }
        public string ref_no { get; set; }
        public Nullable<System.DateTime> issue_date { get; set; }
        public Nullable<int> emp_issue { get; set; }
        public string emp_issue_name { get; set; }
        public Nullable<int> status_doc { get; set; }
        public Nullable<int> step_doc { get; set; }
        public Nullable<int> sec_id { get; set; }
        public Nullable<int> ref_doc { get; set; }
        public Nullable<int> ref_doc_id { get; set; }
        public string ref_book_no { get; set; }
        public string ref_doc_no { get; set; }
        public string ref_tagId { get; set; }
        public Nullable<int> sum_total_num { get; set; }
        public Nullable<decimal> sum_total_cost { get; set; }
        public string note01 { get; set; }
        public string note02 { get; set; }
        public string note03 { get; set; }
        public string note04 { get; set; }
        public string note05 { get; set; }
        public string note06 { get; set; }
        public string note07 { get; set; }
        public string note08 { get; set; }
        public string note09 { get; set; }
        public string note10 { get; set; }
    }
}
