//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pm_menuItems
    {
        public string object_id { get; set; }
        public string object_type { get; set; }
        public int menu_id { get; set; }
    
        public virtual pm_menulist pm_menulist { get; set; }
    }
}
