//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pm_plangroup
    {
        public int pgp_id { get; set; }
        public string pgp_code { get; set; }
        public string pgp_name { get; set; }
        public string pgp_remark { get; set; }
    }
}
