//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pm_userpermissionItems
    {
        public int userid { get; set; }
        public int menu_Id { get; set; }
        public string object_Id { get; set; }
        public int grant_value { get; set; }
    }
}
