//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pm_wo
    {
        public int wo_id { get; set; }
        public string ccode { get; set; }
        public string book_no { get; set; }
        public string doc_no { get; set; }
        public string ref_no { get; set; }
        public Nullable<System.DateTime> wo_date { get; set; }
        public Nullable<int> emp_plan { get; set; }
        public string emp_plan_name { get; set; }
        public Nullable<int> status_doc { get; set; }
        public Nullable<int> step_doc { get; set; }
        public Nullable<int> level_doc { get; set; }
        public Nullable<int> ref_doc_gen { get; set; }
        public Nullable<int> ref_doc_id { get; set; }
        public string ref_book { get; set; }
        public string ref_doc { get; set; }
        public string ref_tagid { get; set; }
        public Nullable<System.DateTime> date_start_wo { get; set; }
        public Nullable<System.DateTime> date_finish_wo { get; set; }
        public Nullable<int> sec_id { get; set; }
        public Nullable<int> duration_time { get; set; }
        public Nullable<decimal> labor_cost { get; set; }
        public Nullable<decimal> other_cost { get; set; }
        public Nullable<int> emp_lab { get; set; }
        public Nullable<int> emp_check { get; set; }
        public string note01 { get; set; }
        public string note02 { get; set; }
        public string note03 { get; set; }
        public string note04 { get; set; }
        public string note05 { get; set; }
        public string note06 { get; set; }
        public string note07 { get; set; }
        public string note08 { get; set; }
        public string note09 { get; set; }
        public string note10 { get; set; }
        public string maccode { get; set; }
        public string sysmp_name { get; set; }
        public string case_name { get; set; }
        public Nullable<int> status_job { get; set; }
        public string emp_lab_name { get; set; }
        public Nullable<int> approve_type { get; set; }
        public Nullable<int> emp_approve { get; set; }
        public string emp_approve_name { get; set; }
    }
}
