//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pm_wp_workinstruction
    {
        public int wpw_id { get; set; }
        public Nullable<int> wp_id { get; set; }
        public Nullable<int> n_step { get; set; }
        public string work_step { get; set; }
    }
}
