//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pm_wp
    {
        public int wp_id { get; set; }
        public string ccode { get; set; }
        public string book_no { get; set; }
        public string doc_no { get; set; }
        public string ref_no { get; set; }
        public Nullable<System.DateTime> plan_date { get; set; }
        public Nullable<int> emp_plan { get; set; }
        public string emp_plan_name { get; set; }
        public Nullable<int> status_doc { get; set; }
        public Nullable<int> step_doc { get; set; }
        public string dec_desc { get; set; }
        public string ro_book { get; set; }
        public string ro_maccode { get; set; }
        public string ro_tagid { get; set; }
        public Nullable<System.DateTime> date_startplan { get; set; }
        public Nullable<System.DateTime> date_finishedplan { get; set; }
        public Nullable<int> duration_time { get; set; }
        public string note01 { get; set; }
        public string note02 { get; set; }
        public string note03 { get; set; }
        public string note04 { get; set; }
        public string note05 { get; set; }
        public string note06 { get; set; }
        public string note07 { get; set; }
        public string note08 { get; set; }
        public string note09 { get; set; }
        public string note10 { get; set; }
        public Nullable<decimal> labor_cost { get; set; }
        public Nullable<decimal> other_cost { get; set; }
        public Nullable<int> priority_n { get; set; }
        public Nullable<int> pm_level { get; set; }
        public Nullable<int> ro_statusjob { get; set; }
        public Nullable<int> sec_id { get; set; }
        public Nullable<int> ref_RO { get; set; }
        public string sysmp_name { get; set; }
        public string case_name { get; set; }
        public Nullable<int> approve_type { get; set; }
        public Nullable<int> emp_approve { get; set; }
        public string emp_approve_name { get; set; }
    }
}
