//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POOption
    {
        public int BrchID { get; set; }
        public string AgingVendor { get; set; }
        public string PO_OverCredit { get; set; }
        public string PO_OverPr { get; set; }
        public string Over_Advan { get; set; }
        public string Pr_Over { get; set; }
        public string Rec_OverPO { get; set; }
        public string Appv_Part { get; set; }
        public string Po_rece { get; set; }
        public string AP_Ship { get; set; }
        public string AP_NoShip { get; set; }
        public string Po_Appvby { get; set; }
        public string Pr_Appvby { get; set; }
        public string Over_Appv { get; set; }
        public string AP_Inv { get; set; }
        public string AP_overAppv { get; set; }
        public string ccode { get; set; }
    }
}
