//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSet_detail
    {
        public int bci_id { get; set; }
        public string count_no { get; set; }
        public string ps_id { get; set; }
        public string pcode { get; set; }
        public string amount { get; set; }
        public string Ps { get; set; }
        public string tpcode { get; set; }
        public string ccode { get; set; }
    }
}
