//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int pro_id { get; set; }
        public string procode { get; set; }
        public string proname1 { get; set; }
        public string proname2 { get; set; }
        public string wpcode { get; set; }
        public string ccode { get; set; }
    }
}
