//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMat
    {
        public string ccode { get; set; }
        public string bcode { get; set; }
        public string fcode { get; set; }
        public string bomcode { get; set; }
        public string oprseq { get; set; }
        public string suboprseq { get; set; }
        public Nullable<int> no { get; set; }
        public string pcode { get; set; }
        public string type { get; set; }
        public Nullable<decimal> num { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> stdyeild { get; set; }
        public string ovhd { get; set; }
        public string cost_ign { get; set; }
        public string mrp { get; set; }
        public string proc { get; set; }
        public string sbst { get; set; }
        public string childbom { get; set; }
        public Nullable<int> typebuffer { get; set; }
    }
}
