//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCG
    {
        public int scg_id { get; set; }
        public string step { get; set; }
        public string ccode { get; set; }
        public string bcode { get; set; }
        public string secode { get; set; }
        public string book { get; set; }
        public string doc { get; set; }
        public Nullable<System.DateTime> scg_date { get; set; }
        public string note { get; set; }
        public Nullable<int> post { get; set; }
        public Nullable<int> SCGstate { get; set; }
        public string statusSCG { get; set; }
        public string note1 { get; set; }
        public string note2 { get; set; }
        public string note3 { get; set; }
        public string note4 { get; set; }
        public string note5 { get; set; }
        public string note6 { get; set; }
        public string note7 { get; set; }
        public string note8 { get; set; }
        public string note9 { get; set; }
        public string note10 { get; set; }
        public string ref_no { get; set; }
        public string TagID { get; set; }
    }
}
