//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCG_Member
    {
        public int scg_id { get; set; }
        public string pcode { get; set; }
        public Nullable<int> PF { get; set; }
        public string wcode { get; set; }
        public string lot { get; set; }
        public Nullable<decimal> increase1 { get; set; }
        public Nullable<decimal> increase2 { get; set; }
        public Nullable<decimal> decrease1 { get; set; }
        public Nullable<decimal> decrease2 { get; set; }
        public Nullable<decimal> cost { get; set; }
        public string note1 { get; set; }
        public string note2 { get; set; }
        public string note3 { get; set; }
        public string note4 { get; set; }
        public string note5 { get; set; }
        public string note6 { get; set; }
        public string note7 { get; set; }
        public string note8 { get; set; }
        public string note9 { get; set; }
        public string note10 { get; set; }
        public Nullable<int> num { get; set; }
    }
}
