//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedualtime_pm
    {
        public int did { get; set; }
        public string ccode { get; set; }
        public string bcode { get; set; }
        public string fcode { get; set; }
        public Nullable<System.DateTime> wdate { get; set; }
        public Nullable<decimal> wtime { get; set; }
        public Nullable<decimal> otime { get; set; }
        public Nullable<decimal> mins { get; set; }
        public string remark { get; set; }
        public Nullable<int> macstate { get; set; }
        public string maccode { get; set; }
        public Nullable<decimal> wtsunk1 { get; set; }
        public Nullable<decimal> wtsunk2 { get; set; }
        public Nullable<decimal> wtsunk3 { get; set; }
        public Nullable<decimal> wtsunk4 { get; set; }
        public Nullable<decimal> wtsunk5 { get; set; }
        public Nullable<decimal> wtsunk6 { get; set; }
        public Nullable<decimal> wtmonk1 { get; set; }
        public Nullable<decimal> wtmonk2 { get; set; }
        public Nullable<decimal> wtmonk3 { get; set; }
        public Nullable<decimal> wtmonk4 { get; set; }
        public Nullable<decimal> wtmonk5 { get; set; }
        public Nullable<decimal> wtmonk6 { get; set; }
        public Nullable<decimal> wttuek1 { get; set; }
        public Nullable<decimal> wttuek2 { get; set; }
        public Nullable<decimal> wttuek3 { get; set; }
        public Nullable<decimal> wttuek4 { get; set; }
        public Nullable<decimal> wttuek5 { get; set; }
        public Nullable<decimal> wttuek6 { get; set; }
        public Nullable<decimal> wtwedk1 { get; set; }
        public Nullable<decimal> wtwedk2 { get; set; }
        public Nullable<decimal> wtwedk3 { get; set; }
        public Nullable<decimal> wtwedk4 { get; set; }
        public Nullable<decimal> wtwedk5 { get; set; }
        public Nullable<decimal> wtwedk6 { get; set; }
        public Nullable<decimal> wtthuk1 { get; set; }
        public Nullable<decimal> wtthuk2 { get; set; }
        public Nullable<decimal> wtthuk3 { get; set; }
        public Nullable<decimal> wtthuk4 { get; set; }
        public Nullable<decimal> wtthuk5 { get; set; }
        public Nullable<decimal> wtthuk6 { get; set; }
        public Nullable<decimal> wtfrik1 { get; set; }
        public Nullable<decimal> wtfrik2 { get; set; }
        public Nullable<decimal> wtfrik3 { get; set; }
        public Nullable<decimal> wtfrik4 { get; set; }
        public Nullable<decimal> wtfrik5 { get; set; }
        public Nullable<decimal> wtfrik6 { get; set; }
        public Nullable<decimal> wtsatk1 { get; set; }
        public Nullable<decimal> wtsatk2 { get; set; }
        public Nullable<decimal> wtsatk3 { get; set; }
        public Nullable<decimal> wtsatk4 { get; set; }
        public Nullable<decimal> wtsatk5 { get; set; }
        public Nullable<decimal> wtsatk6 { get; set; }
        public Nullable<decimal> sunb1 { get; set; }
        public Nullable<decimal> sunb2 { get; set; }
        public Nullable<decimal> sunb3 { get; set; }
        public Nullable<decimal> sunb4 { get; set; }
        public Nullable<decimal> sunb5 { get; set; }
        public Nullable<decimal> sunb6 { get; set; }
        public Nullable<decimal> monb1 { get; set; }
        public Nullable<decimal> monb2 { get; set; }
        public Nullable<decimal> monb3 { get; set; }
        public Nullable<decimal> monb4 { get; set; }
        public Nullable<decimal> monb5 { get; set; }
        public Nullable<decimal> monb6 { get; set; }
        public Nullable<decimal> tueb1 { get; set; }
        public Nullable<decimal> tueb2 { get; set; }
        public Nullable<decimal> tueb3 { get; set; }
        public Nullable<decimal> tueb4 { get; set; }
        public Nullable<decimal> tueb5 { get; set; }
        public Nullable<decimal> tueb6 { get; set; }
        public Nullable<decimal> wedb1 { get; set; }
        public Nullable<decimal> wedb2 { get; set; }
        public Nullable<decimal> wedb3 { get; set; }
        public Nullable<decimal> wedb4 { get; set; }
        public Nullable<decimal> wedb5 { get; set; }
        public Nullable<decimal> wedb6 { get; set; }
        public Nullable<decimal> thub1 { get; set; }
        public Nullable<decimal> thub2 { get; set; }
        public Nullable<decimal> thub3 { get; set; }
        public Nullable<decimal> thub4 { get; set; }
        public Nullable<decimal> thub5 { get; set; }
        public Nullable<decimal> thub6 { get; set; }
        public Nullable<decimal> frib1 { get; set; }
        public Nullable<decimal> frib2 { get; set; }
        public Nullable<decimal> frib3 { get; set; }
        public Nullable<decimal> frib4 { get; set; }
        public Nullable<decimal> frib5 { get; set; }
        public Nullable<decimal> frib6 { get; set; }
        public Nullable<decimal> satb1 { get; set; }
        public Nullable<decimal> satb2 { get; set; }
        public Nullable<decimal> satb3 { get; set; }
        public Nullable<decimal> satb4 { get; set; }
        public Nullable<decimal> satb5 { get; set; }
        public Nullable<decimal> satb6 { get; set; }
        public Nullable<decimal> fintim { get; set; }
        public Nullable<decimal> fin_mon { get; set; }
        public Nullable<decimal> fin_tue { get; set; }
        public Nullable<decimal> fin_wed { get; set; }
        public Nullable<decimal> fin_thu { get; set; }
        public Nullable<decimal> fin_fri { get; set; }
        public Nullable<decimal> fin_sat { get; set; }
    }
}
