//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scrap
    {
        public int scid { get; set; }
        public string scode { get; set; }
        public string scname1 { get; set; }
        public string scname2 { get; set; }
        public string ccode { get; set; }
    }
}
