//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public int sec_id { get; set; }
        public string secode { get; set; }
        public string sename1 { get; set; }
        public string sename2 { get; set; }
        public string dcode { get; set; }
        public string ccode { get; set; }
    }
}
