//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetProductloss
    {
        public int id { get; set; }
        public string ccode { get; set; }
        public string pcode { get; set; }
        public Nullable<decimal> stN { get; set; }
        public Nullable<decimal> fnN { get; set; }
        public Nullable<decimal> lossN { get; set; }
    }
}
