//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shelf
    {
        public int Shel_id { get; set; }
        public string shelcode { get; set; }
        public string loccode { get; set; }
        public string wcode { get; set; }
        public string shelname1 { get; set; }
        public string shelname2 { get; set; }
        public string shelposition { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string shelcolor { get; set; }
        public Nullable<decimal> shelcapacity { get; set; }
        public Nullable<decimal> shelvolume { get; set; }
        public Nullable<double> IsDelete { get; set; }
        public Nullable<int> SortID { get; set; }
        public string ArrayLocation { get; set; }
    }
}
