//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOCreditApprov
    {
        public int CreditID { get; set; }
        public Nullable<int> ApprovBy { get; set; }
        public string Cuscode { get; set; }
        public string DocuNo { get; set; }
        public System.DateTime DocuDate { get; set; }
        public Nullable<System.DateTime> CreditStartDate { get; set; }
        public Nullable<System.DateTime> CreditEndDate { get; set; }
        public Nullable<decimal> CreditAmnt { get; set; }
        public string Remark { get; set; }
        public string CreditFlag { get; set; }
        public Nullable<int> CreditLimitDay { get; set; }
        public Nullable<decimal> RemaAmnt { get; set; }
        public string ccode { get; set; }
    }
}
