//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOOption
    {
        public int BrchID { get; set; }
        public string CreditTermQuot { get; set; }
        public string CreditTermSO { get; set; }
        public string CreditTermOC { get; set; }
        public string CreditTermBL { get; set; }
        public string AmtOverLimit { get; set; }
        public string SOExcConfirmOrder { get; set; }
        public string SaleExcSOAmt { get; set; }
        public string WarnningRecDep { get; set; }
        public string SaleLowCost { get; set; }
        public string OverQue { get; set; }
        public string CNOverAmnt { get; set; }
        public string RefQuo { get; set; }
        public string AgingCust { get; set; }
        public string ccode { get; set; }
    }
}
