//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stdoperate
    {
        public int sto_id { get; set; }
        public string stocode { get; set; }
        public string stoname1 { get; set; }
        public string stoname2 { get; set; }
        public string ccode { get; set; }
        public string bcode { get; set; }
        public string fcode { get; set; }
        public string secode { get; set; }
        public string wctcode { get; set; }
        public Nullable<decimal> stocap { get; set; }
    }
}
