//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public string ccode { get; set; }
        public string bcode { get; set; }
        public string wcode { get; set; }
        public Nullable<int> did { get; set; }
        public string doctype { get; set; }
        public string book { get; set; }
        public string doc { get; set; }
        public Nullable<System.DateTime> fddate { get; set; }
        public string pcode { get; set; }
        public string lot { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<decimal> increase { get; set; }
        public Nullable<decimal> outcrease { get; set; }
        public string status { get; set; }
        public int bciid { get; set; }
    }
}
