//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int sup_id { get; set; }
        public string supcode { get; set; }
        public string supname1 { get; set; }
        public string supname11 { get; set; }
        public string supname2 { get; set; }
        public string supname21 { get; set; }
        public string supaddress1 { get; set; }
        public string supaddress2 { get; set; }
        public string supzip { get; set; }
        public string suptel { get; set; }
        public string supfax { get; set; }
        public string supmobile { get; set; }
        public Nullable<System.DateTime> dateinact { get; set; }
        public Nullable<bool> status { get; set; }
        public string p_id { get; set; }
        public string t_id { get; set; }
        public string niti { get; set; }
        public string acc_code { get; set; }
        public Nullable<int> gsupid { get; set; }
        public string contaddress1 { get; set; }
        public string contaddress2 { get; set; }
        public string contzip { get; set; }
        public string notebill { get; set; }
        public string noteth { get; set; }
        public string noteen { get; set; }
        public string credittermday { get; set; }
        public Nullable<int> creditmoney { get; set; }
        public string contname { get; set; }
        public string ncostcode { get; set; }
        public string ndiscountcode { get; set; }
        public string note1 { get; set; }
        public string note2 { get; set; }
        public string note3 { get; set; }
        public string note4 { get; set; }
        public string note5 { get; set; }
        public string note6 { get; set; }
        public string note7 { get; set; }
        public string note8 { get; set; }
        public string note9 { get; set; }
        public string note10 { get; set; }
        public string ccode { get; set; }
    }
}
