//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_purchase_order
    {
        public int po_id { get; set; }
        public string ccode { get; set; }
        public string bcode { get; set; }
        public string po { get; set; }
        public string po_no { get; set; }
        public string ref_no { get; set; }
        public Nullable<System.DateTime> po_date { get; set; }
        public Nullable<int> cust_id { get; set; }
        public string secode { get; set; }
        public string curcode { get; set; }
        public Nullable<decimal> curexchange { get; set; }
        public Nullable<decimal> vattype { get; set; }
        public string vat { get; set; }
        public Nullable<int> genmp { get; set; }
        public Nullable<int> POstate { get; set; }
        public string statusPO { get; set; }
        public Nullable<bool> verify { get; set; }
        public Nullable<System.DateTime> verify_date { get; set; }
        public Nullable<decimal> total_qty { get; set; }
        public Nullable<decimal> total_discount_p { get; set; }
        public Nullable<decimal> total_discount_c { get; set; }
        public Nullable<decimal> total_b_vat { get; set; }
        public Nullable<decimal> total_vat { get; set; }
        public Nullable<decimal> total_net { get; set; }
        public string im_status { get; set; }
        public string note1 { get; set; }
        public string note2 { get; set; }
        public string note3 { get; set; }
        public string note4 { get; set; }
        public string note5 { get; set; }
        public string note6 { get; set; }
        public string note7 { get; set; }
        public string note8 { get; set; }
        public string note9 { get; set; }
        public string note10 { get; set; }
        public Nullable<System.DateTime> send_date { get; set; }
        public Nullable<int> sendnumdate { get; set; }
        public string createBook { get; set; }
        public string Savestatus { get; set; }
        public string procode { get; set; }
        public Nullable<bool> complete { get; set; }
        public string ref_pc { get; set; }
        public string fromPR { get; set; }
        public string status_ref { get; set; }
        public string ref_tr { get; set; }
    }
}
