//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public int uid { get; set; }
        public string ucode { get; set; }
        public string uname1 { get; set; }
        public string uname2 { get; set; }
        public string ccode { get; set; }
    }
}
