//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserName
    {
        public int userid { get; set; }
        public string UserName1 { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsNormal { get; set; }
        public string ecode { get; set; }
        public string ccode { get; set; }
    }
}
