//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class W1PDocNo
    {
        public int w1pdocid { get; set; }
        public string w1pdocno1 { get; set; }
        public string w1pdocname { get; set; }
        public string bcode { get; set; }
        public string ccode { get; set; }
    }
}
