//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystemProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF
    {
        public int wf_id { get; set; }
        public string step { get; set; }
        public string ccode { get; set; }
        public string bcode { get; set; }
        public string secode { get; set; }
        public Nullable<int> motype { get; set; }
        public string mobook { get; set; }
        public string modoc { get; set; }
        public string book { get; set; }
        public string doc { get; set; }
        public string ref_no { get; set; }
        public Nullable<System.DateTime> wf_date { get; set; }
        public string wcode1 { get; set; }
        public string wcode2 { get; set; }
        public Nullable<int> ref_mo { get; set; }
        public string comment { get; set; }
        public Nullable<int> WFstate { get; set; }
        public string statusWF { get; set; }
        public Nullable<decimal> totalqty { get; set; }
        public Nullable<decimal> totalprice { get; set; }
        public string note1 { get; set; }
        public string note2 { get; set; }
        public string note3 { get; set; }
        public string note4 { get; set; }
        public string note5 { get; set; }
        public string note6 { get; set; }
        public string note7 { get; set; }
        public string note8 { get; set; }
        public string note9 { get; set; }
        public string note10 { get; set; }
    }
}
